version: "3"
services:
  nginx:
    build: ./docker/nginx/
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./laravel:/home/www-data/workspace/laravel
    depends_on:
      - php
    environment:
      - TZ=${TZ}

  php:
    build: ./docker/php
    volumes:
      - ./:/home/www-data/workspace
    environment:
      - TZ=${TZ}
    extra_hosts:
      - "host.docker.internal:192.168.1.7"

  db:
    build: ./docker/mysql
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TZ}
volumes:
  db-store:
